export const SKILLS = [
  {
    id: 1,
    section: 'Front-End',
    skillsList: [
      {
        id: '1.1',
        skill: 'React',
        icon: '/assets/images/skills-icons/react.svg',
        progress: 95,
        showsidebar: true,
      },
      {
        id: '1.2',
        skill: 'Redux',
        icon: '/assets/images/skills-icons/redux.svg',
        progress: 90,
        showsidebar: true,
      },
      {
        id: '1.3',
        skill: 'Angular',
        icon: '/assets/images/skills-icons/angular.svg',
        progress: 95,
        showsidebar: true,
      },
      {
        id: '1.4',
        skill: 'Vue',
        icon: '/assets/images/skills-icons/vue.svg',
        progress: 93,
        showsidebar: true,
      },
      {
        id: '1.5',
        skill: 'JavaScript',
        icon: '/assets/images/skills-icons/javascript.svg',
        progress: 98,
        showsidebar: true,
      },
      {
        id: '1.6',
        skill: 'TypeScript',
        icon: '/assets/images/skills-icons/typescript.svg',
        progress: 95,
        showsidebar: true,
      },
    ],
  },
  {
    id: 2,
    section: 'Back-End',
    skillsList: [
      {
        id: '2.1',
        skill: 'Node JS',
        icon: '/assets/images/skills-icons/node-js.svg',
        progress: 85,
        showsidebar: true,
      },
      {
        id: '2.2',
        skill: 'PHP',
        icon: '/assets/images/skills-icons/php.svg',
        progress: 85,
        showsidebar: true,
      },
      {
        id: '2.3',
        skill: 'Laravel',
        icon: '/assets/images/skills-icons/laravel.svg',
        progress: 80,
        showsidebar: true,
      },
      {
        id: '2.4',
        skill: 'Python',
        icon: '/assets/images/skills-icons/python.svg',
        progress: 60,
        showsidebar: false,
      },
      {
        id: '2.5',
        skill: 'Java',
        icon: '/assets/images/skills-icons/java.svg',
        progress: 40,
        showsidebar: false,
      },
    ],
  },
  {
    id: 3,
    section: 'Database',
    skillsList: [
      {
        id: '3.1',
        skill: 'PostgreSQL',
        icon: '/assets/images/skills-icons/postgresql.svg',
        progress: 95,
        showsidebar: true,
      },

      {
        id: '3.2',
        skill: 'MySQL',
        icon: '/assets/images/skills-icons/mysql.svg',
        progress: 95,
        showsidebar: true,
      },
      {
        id: '3.3',
        skill: 'MongoDB',
        icon: '/assets/images/skills-icons/mongodb.svg',
        progress: 75,
        showsidebar: false,
      },
      {
        id: '3.4',
        skill: 'Firebase',
        icon: '/assets/images/skills-icons/firebase.svg',
        progress: 85,
        showsidebar: true,
      },
      {
        id: '3.5',
        skill: 'Redis',
        icon: '/assets/images/skills-icons/redis.svg',
        progress: 75,
        showsidebar: true,
      },
    ],
  },
  {
    id: 4,
    section: 'Other',
    skillsList: [
      {
        id: '4.1',
        skill: 'GitHub',
        icon: '/assets/images/skills-icons/github.svg',
        progress: 100,
        showsidebar: false,
      },
      {
        id: '4.2',
        skill: 'Jira',
        icon: '/assets/images/skills-icons/jira.svg',
        progress: 100,
        showsidebar: false,
      },
      {
        id: '4.3',
        skill: 'Gulp',
        icon: '/assets/images/skills-icons/gulp.svg',
        progress: 100,
        showsidebar: false,
      },
      {
        id: '4.4',
        skill: 'Webpack',
        icon: '/assets/images/skills-icons/webpack.svg',
        progress: 100,
        showsidebar: false,
      },
      {
        id: '4.5',
        skill: 'GitLab',
        icon: '/assets/images/skills-icons/gitlab.svg',
        progress: 100,
        showsidebar: false,
      },
    ],
  },
];
